["SPY", "QQQ", "TQQQ", 'SOXL', "MSFT", "AAPL",
                                            "GOOG", "GOOGL", "AMZN", "NVDA", "META", "LLY", "TSLA",
    "AVGO", "V", "JPM", "UNH", "WMT", "MA", "XOM", "JNJ", "PG", "HD", "MRK", "ORCL",
    "COST", "ABBV", "CVX", "CRM", "ADBE", "AMD", "BAC", "KO", "NFLX", "PEP", "ACN",
    "TMO", "MCD", "CSCO", "LIN", "ABT", "TMUS", "DHR", "DIS", "INTC", "INTU", "WFC",
    "CMCSA", "VZ", "IBM", "CAT", "QCOM", "NOW", "AMGN", "NKE", "PFE", "AXP", "BX",
    "UNP", "GE", "SPGI", "UBER", "TXN", "AMAT", "PM", "MS", "ISRG", "COP", "SYK",
    "BA", "LMT", "MDT", "GS", "FDX", "TGT", "HON", "MMM", "RTX", "DE", "SO", "C",
    "NET", "ANET", "PANW", "DDOG", "CDNS", "CMG", "SNPS", "SOFI", "QLD", "RBLX",
    "SNOW", "CPRT", "FTEC", "METV", "QQQM", "KNSL", "MPWR", "SOXX", "PTC", "BRO",
    "TWLO", "TYL", "FTNT", "ADSK", "APH", "CDW", "VEEV", "SPYG", "VTI", "VOO",
    "EQIX", "MSI", "ON", "BLK", "WM", "QQQJ", "ADI", "SCHD", "CSGP", "JEPI", 
    ],
